package unibo.footstats.utility;

public enum Context {
    HOME_PAGE,
    PLAYER_SEARCH,
    PLAYER_STATISTICS,
    TEAM_SEARCH,
    TOURNAMENT_SEARCH,
    CLUB_COMPETITION,
    NATIONAL_TEAM_COMPETITION,
    RANKING,
    TRANSFER_MARKET,
    REQUEST,
    LOGIN
}
